### ISSUE TITLE
为什么会有 baiduyun_install ？

### ISSUE THREAD

**Issue by bao3** [leenchan/docker-alpine-lnmp#1]
```
baiduyun_install() {
	docker_opt 'pcs'
}
```
lnmp 里带个 baiduyun 是有什么用？

**Comment by leenchan** [comment]
这是我自用的docker镜像，所以不单单是lnmp，baiduyun 是 github 上面那个pcs，上面有详细说明的

**Comment by bao3** [comment]
所以我改造成自己的，就只要删除 run/ 下面对应的脚本就好了？

**Comment by leenchan** [comment]
直接注释掉docker.sh里面的就可以了，run里面没有的，pcs只是个命令，不会开机启动
